### PR TITLE
build: prevent lib/Buffer.php to be always autoloaded by Composer

### LINKED ISSUE #2: Prevent Buffer.php to be always autoloaded
Hola!

Could it be possible to update the package `composer.json` and replace the `"files"` key under `"autoload"` with `"classmap"`?

It should work the same and prevent the `Buffer.php` file to be loaded in every request.

Gracias!

### PR DESCRIPTION
**Pull request by javiermarinros**
Fix #2

### CODE REVIEW

**Comment by miguelbemartin** [comment]
Thanks

**Comment by javiermarinros** [comment]
Could you publish a release including this change? Thank you!

**Comment by miguelbemartin** [comment]
@javiermarinros - Done: https://github.com/miguelbemartin/buffer-sdk-php/releases/tag/v1.0.4

**Comment by javiermarinros** [comment]
Thank you @miguelbemartin 

FYI, Packagist is complaining about this update:

> Skipped branch master, Invalid package information: 
> replace.miguelbemartin/buffer-sdk-php : a package cannot set a replace on itself

**Comment by miguelbemartin** [comment]
@javiermarinros - I've added you to this repo as a collaborator. I am not actively using this library anymore and it was too much time ago when I created this library. I am not familiar with packagist system. Could you try to fix it?

**Comment by javiermarinros** [comment]
Sure @miguelbemartin I will push a fix. Thank you for adding me as collaborator!

**Pull request merged**
